### ISSUE TITLE
daily useage may be 4 hrs plus-phone mustnt sleep or runout of juice

### ISSUE THREAD

**Issue by wbridge** [mattclarkdotnet/viscompass#20]

**Comment by mattclarkdotnet** [comment]
I think this is a part of the overall interaction model.  Let's set an expectation that the phone is fully charged and preferably plugged in to a power supply.  It's not something the app can control but by setting the right user expectations we can create a good experience.

**Comment by wbridge** [comment]
Amazing work on the VISCompass Matt – great stuff

It’ll be Monday before I get to look at it/respond .... maybe talk soon thereafter

Wx

**Comment by mattclarkdotnet** [comment]
Note that the app forces the phone to stay awake while in use because sleeping while navigating is not a good plan.

To save battery without interfering with the app users can a) set an iOS phone to 'Airplane Mode', and b) enable 'low power mode'.

'Airplane mode' may be a good recommendation anyway as it will avoid awkward incoming calls.

With both settings enabled a phone on full charge should get 6+ hours of usage.

**Comment by wbridge** [comment]
Just fine -agreed

Will Bridge
07802 306006
mail@willbridge.com or wandj@willbridge.com

**Comment by mattclarkdotnet** [comment]
Another note, after turning on Airplane Mode users with BT headphones will need to re-enable bluetooth separately.
